-- ==================================================
-- F1.1: CUSTOMER ORDER DISTRIBUTION
-- ==================================================

-- Business Question:
-- How are customers distributed by number of orders?
USE retail_business_db;

WITH customer_order_summary AS(
SELECT
	c.customer_unique_id,
    COUNT(vo.order_id) AS order_per_customer
FROM valid_orders vo
INNER JOIN customers c
ON c.customer_id = vo.customer_id
WHERE c.customer_unique_id IS NOT NULL
	AND vo.order_id IS NOT NULL
GROUP BY c.customer_unique_id
    )
    
SELECT
	COUNT(customer_unique_id) AS customer_order_frequency,
    order_per_customer
FROM customer_order_summary
GROUP BY order_per_customer;

-- Finding:
-- Customer purchasing behavior is heavily concentrated among one-time buyers.
-- 93,074 customers placed only one order, while repeat customers represented a much smaller portion of the customer base.
-- Only a few customers placed more than four orders, with the highest observed customer placing 17 orders.


-- ==================================================
-- F1.2: ONE-TIME VS REPEAT CUSTOMER SEGMENTATION
-- ==================================================

-- Business Question:
-- How many customers are one-time buyers,
-- and how many are repeat buyers?

WITH customer_order_summary AS(
SELECT
	c.customer_unique_id,
    COUNT(vo.order_id) AS order_per_customer
FROM valid_orders vo
INNER JOIN customers c
ON c.customer_id = vo.customer_id
WHERE c.customer_unique_id IS NOT NULL
	AND vo.order_id IS NOT NULL
GROUP BY c.customer_unique_id
	),
    
customer_segmentation AS(
SELECT
	customer_unique_id,
    order_per_customer,
	(
		CASE
			WHEN order_per_customer > 1 THEN 'Repeated'
            ELSE 'One_Time'
		END
        ) AS customer_segmentation
FROM customer_order_summary)

SELECT 
	customer_segmentation,
	COUNT(customer_segmentation) AS total_customers
FROM customer_segmentation
GROUP BY customer_segmentation;

-- Finding:
-- The customer base is dominated by one-time buyers, with 93,074 customers placing only one order.
-- Only 2,994 customers made repeat purchases, indicating a relatively low customer retention rate.
-- The business appears to rely heavily on acquiring new customers rather than generating repeat purchases from existing customers.

-- ==================================================
-- F1.3: HIGH-VALUE CUSTOMERS
-- ==================================================

-- Business Question:
-- Who are the highest-value customers?
SELECT
	c.customer_unique_id,
    SUM(oi.price + oi.freight_value) AS total_revenue_per_customer
FROM valid_orders vo
INNER JOIN customers c
ON c.customer_id = vo.customer_id
INNER JOIN order_items oi
ON oi.order_id = vo.order_id
GROUP BY c.customer_unique_id
ORDER BY total_revenue_per_customer DESC
LIMIT 10;

-- Finding:
-- Customer spending is highly concentrated among a small group of customers.
-- The highest-value customer generated 13,664.08 in total revenue.
-- The top 10 customers each generated more than 4,600 in revenue.
-- These customers represent the business's most valuable customer segment and may be important for retention and loyalty initiatives.


-- ==================================================
-- F1.4: REVENUE CONTRIBUTION BY CUSTOMER SEGMENT
-- ==================================================

-- Business Question:
-- How much revenue is generated by repeat customers versus one-time customers?
WITH customer_order_summary AS(
SELECT
	c.customer_unique_id,
    COUNT(oi.order_id) AS total_order_per_cust,
    SUM(oi.price + oi.freight_value) AS total_rev_per_cust
FROM valid_orders vo
INNER JOIN customers c
ON c.customer_id = vo.customer_id
INNER JOIN order_items oi
ON oi.order_id = vo.order_id
WHERE c.customer_unique_id IS NOT NULL 
	AND oi.order_id IS NOT NULL
GROUP BY c.customer_unique_id
),

customer_segmentation AS(
SELECT
	total_order_per_cust,
	total_rev_per_cust,
	(
		CASE
			WHEN total_order_per_cust > 1 THEN 'Repeated'
            ELSE 'One_Time'
		END
        ) AS customer_segmentation
FROM customer_order_summary
)

SELECT
	customer_segmentation,
	COUNT(customer_segmentation) AS customers_seg_count,
    SUM(total_rev_per_cust) AS total_rev_per_seg
FROM customer_segmentation
GROUP BY customer_segmentation;

-- Finding:
-- One-time customers generated 12.70 million in revenue, while repeat customers generated 3.14 million.
-- Although repeat customers represent a much smaller portion of the customer base, they contributed nearly 20% of total revenue.
-- The business relies heavily on one-time customers for revenue generation, but repeat customers remain a valuable revenue segment.


-- ==================================================
-- F2: PRODUCT CONCENTRATION ANALYSIS
-- ==================================================


-- ==================================================
-- F2.1: TOP REVENUE-GENERATING PRODUCT CATEGORIES
-- ==================================================

-- Business Question:
-- Which product categories generated the highest revenue?
SELECT
	p.product_category_name,
    COUNT(oi.order_id) AS order_per_product,
    SUM(oi.price + oi.freight_value) AS total_rev_per_product
FROM order_items oi
LEFT JOIN products p
ON p.product_id = oi.product_id
WHERE oi.order_id IS NOT NULL
	AND p.product_id IS NOT NULL
GROUP BY p.product_category_name
ORDER BY SUM(oi.price + oi.freight_value) DESC
LIMIT 10;



-- ==================================================
-- F2.2: HIGHEST AVERAGE REVENUE PER ORDER BY CATEGORY
-- ==================================================

-- Business Question:
-- Which product categories generate the highest average revenue per order?


WITH product_summary AS(
SELECT
	p.product_category_name,
    COUNT(DISTINCT oi.order_id) AS order_per_product,
    SUM(oi.price + oi.freight_value) AS total_rev_per_product
FROM order_items oi
LEFT JOIN products p
ON p.product_id = oi.product_id
WHERE oi.order_id IS NOT NULL
	AND p.product_id IS NOT NULL
GROUP BY p.product_category_name
)

SELECT
	product_category_name,
    (total_rev_per_product / order_per_product) AS avg_rev_per_category
FROM product_summary
ORDER BY (total_rev_per_product / order_per_product) DESC
LIMIT 10;


-- ==================================================
-- F3: CUSTOMER PURCHASE BEHAVIOR ANALYSIS
-- ==================================================


-- ==================================================
-- F3.1: AVERAGE PRODUCTS PURCHASED PER CUSTOMER
-- ==================================================

-- Business Question:
-- How many products does the average customer purchase?

SELECT 
	(COUNT(oi.order_item_id) / COUNT(DISTINCT c.customer_unique_id)) AS avg_purchase_items
FROM valid_orders vo
INNER JOIN customers c
ON c.customer_id = vo.customer_id
INNER JOIN order_items oi
ON oi.order_id = vo.order_id;

-- Key Insight:
-- Customers purchased an average of 1.18 products per customer.
-- This suggests that most customers bought a single item,
-- with relatively few customers purchasing multiple products.


-- ==================================================
-- F3.2: AVERAGE CUSTOMER SPEND
-- ==================================================

-- Business Question:
-- How much does the average customer spend?
WITH customer_spending AS (
    SELECT
        c.customer_unique_id,
        SUM(oi.price + oi.freight_value) AS total_customer_spend
    FROM valid_orders vo
    INNER JOIN customers c
        ON c.customer_id = vo.customer_id
    INNER JOIN order_items oi
        ON oi.order_id = vo.order_id
    GROUP BY c.customer_unique_id
)

SELECT
    AVG(total_customer_spend) AS avg_customer_spend
FROM customer_spending;

-- Key Insight:
-- The average customer spent approximately 166.03.
-- This suggests that customer spending is relatively concentrated
-- around low-to-moderate purchase values, with a smaller group of
-- customers contributing significantly higher spending amounts.

-- ==================================================
-- F3.3: ORDER FREQUENCY VS CUSTOMER SPENDING
-- ==================================================

-- Business Question:
-- What is the relationship between order frequency and customer spending?

WITH customer_behavior AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT vo.order_id) AS total_orders,
        SUM(oi.price + oi.freight_value) AS total_spend
    FROM valid_orders vo
    INNER JOIN customers c
        ON c.customer_id = vo.customer_id
    INNER JOIN order_items oi
        ON oi.order_id = vo.order_id
    GROUP BY c.customer_unique_id
)

SELECT
    customer_unique_id,
    total_orders,
    total_spend
FROM customer_behavior
ORDER BY total_orders DESC, total_spend DESC;

-- Key Insight:
-- Customers who place more orders do not necessarily spend more money.
-- While some high-frequency customers generate high revenue,
-- others place many orders with relatively low spending.
-- This suggests that purchase frequency alone is not a reliable indicator
-- of customer value.


-- ==================================================
-- F4: ORDER LIFECYCLE ANALYSIS
-- ==================================================

-- ==================================================
-- F4.1: LONGEST ORDER LIFECYCLE STAGE
-- ==================================================

-- Business Question:
-- Which stage of the order lifecycle takes the longest time?

SELECT
    ROUND(AVG(TIMESTAMPDIFF(HOUR,
        order_purchase_timestamp,
        order_approved_at)), 2) AS approval_time_hours,

    ROUND(AVG(TIMESTAMPDIFF(HOUR,
        order_approved_at,
        order_delivered_carrier_date)), 2) AS shipping_time_hours,

    ROUND(AVG(TIMESTAMPDIFF(HOUR,
        order_delivered_carrier_date,
        order_delivered_customer_date)), 2) AS delivery_time_hours

FROM valid_orders
WHERE order_purchase_timestamp IS NOT NULL
    AND order_approved_at IS NOT NULL
    AND order_delivered_carrier_date IS NOT NULL
    AND order_delivered_customer_date IS NOT NULL;
    
-- Key Insight:
-- The final delivery stage (carrier to customer) is the longest
-- stage in the order lifecycle, averaging 223.51 hours.
--
-- This stage accounts for the majority of fulfillment time,
-- indicating that last-mile delivery is the primary operational
-- bottleneck in the order process.


-- ==================================================
-- F4.2: SHIPPING TIME FOR DELAYED VS ON-TIME ORDERS
-- ==================================================

-- Business Question:
-- Do delayed deliveries have significantly longer shipping times?

SELECT
    CASE
        WHEN order_delivered_customer_date > order_estimated_delivery_date
        THEN 'Delayed'
        ELSE 'On Time'
    END AS delivery_status,

    ROUND(
        AVG(
            TIMESTAMPDIFF(
                HOUR,
                order_approved_at,
                order_delivered_carrier_date
            )
        ),
        2
    ) AS avg_shipping_time_hours

FROM valid_orders

WHERE order_approved_at IS NOT NULL
    AND order_delivered_carrier_date IS NOT NULL
    AND order_delivered_customer_date IS NOT NULL
    AND order_estimated_delivery_date IS NOT NULL

GROUP BY delivery_status;

-- Key Insight:
-- Delayed orders spent significantly longer in the shipping stage
-- than on-time orders.
--
-- On-time orders averaged 61.31 hours between approval and carrier handoff,
-- while delayed orders averaged 127.18 hours.
--
-- Delayed orders required approximately twice the shipping time of
-- on-time orders, suggesting that shipping delays are a major contributor
-- to late deliveries.  


-- ==================================================
-- F4.3: MONTHLY LATE DELIVERY RATE
-- ==================================================

-- Business Question:
-- Which month recorded the highest late delivery rate?  

SELECT
    DATE_FORMAT(order_purchase_timestamp, '%Y-%m') AS month,

    COUNT(*) AS total_orders,

    SUM(
        CASE
            WHEN order_delivered_customer_date >
                 order_estimated_delivery_date
            THEN 1
            ELSE 0
        END
    ) AS late_orders,

    ROUND(
        SUM(
            CASE
                WHEN order_delivered_customer_date >
                     order_estimated_delivery_date
                THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),
        2
    ) AS late_delivery_rate_pct

FROM valid_orders

WHERE order_purchase_timestamp IS NOT NULL
    AND order_delivered_customer_date IS NOT NULL
    AND order_estimated_delivery_date IS NOT NULL

GROUP BY DATE_FORMAT(order_purchase_timestamp, '%Y-%m')
ORDER BY late_delivery_rate_pct DESC;

-- Key Insight:
-- Among months with meaningful order volume,
-- March 2018 recorded the highest late delivery rate (21.36%),
-- followed by February 2018 (16.00%) and November 2017 (14.31%).
--
-- These periods may indicate capacity constraints,
-- logistics bottlenecks, or seasonal demand pressure
-- affecting delivery performance.
